[workspace]
authors = ["Raniere Silva <raniere@rgaiacs.com>"]
channels = ["conda-forge"]
name = "scicoco-pixi"
platforms = ["win-64", "linux-64", "osx-64", "osx-arm64"]
version = "0.1.0"

[environments.speaker.dependencies]
quarto = ">=1.9.38,<2"

[environments.speaker.tasks.preview]
cmd = "quarto preview --no-browser"

[environments.speaker.tasks.render]
cmd = "quarto render --to html"

[environments.spdx.dependencies]
reuse = ">=6.2.0,<7"

[environments.spdx.tasks.lint]
cmd = "reuse lint"

[environments.spdx.tasks.annotate]
cmd = "reuse annotate --fallback-dot-license"